// <auto-generated />
namespace HRMS.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class updates17 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updates17));
        
        string IMigrationMetadata.Id
        {
            get { return "202202281551128_updates17"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
