//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMS.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class HResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal HResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HRMS.Resources.HResource", typeof(HResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المناطق.
        /// </summary>
        public static string Areas {
            get {
                return ResourceManager.GetString("Areas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الفروع.
        /// </summary>
        public static string Branches {
            get {
                return ResourceManager.GetString("Branches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عرضة.
        /// </summary>
        public static string Casual {
            get {
                return ResourceManager.GetString("Casual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تغيير كلمة المرور.
        /// </summary>
        public static string ChangePassword {
            get {
                return ResourceManager.GetString("ChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to غلق.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تأكيد كلمة المرور.
        /// </summary>
        public static string ConfirmNewPassword {
            get {
                return ResourceManager.GetString("ConfirmNewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جميع الحقوق محفوظة الي.
        /// </summary>
        public static string CopyRights {
            get {
                return ResourceManager.GetString("CopyRights", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الرئييسية.
        /// </summary>
        public static string Dashboard {
            get {
                return ResourceManager.GetString("Dashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الأقسام.
        /// </summary>
        public static string Departments {
            get {
                return ResourceManager.GetString("Departments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أنواع اثبات الشخصية.
        /// </summary>
        public static string IDTypes {
            get {
                return ResourceManager.GetString("IDTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الرصيد الأفتتاحي.
        /// </summary>
        public static string InitialBalance {
            get {
                return ResourceManager.GetString("InitialBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المراسلات الداخلية.
        /// </summary>
        public static string InternalMessaging {
            get {
                return ResourceManager.GetString("InternalMessaging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الوظائف.
        /// </summary>
        public static string Jobs {
            get {
                return ResourceManager.GetString("Jobs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تسجيل خروج.
        /// </summary>
        public static string LogOut {
            get {
                return ResourceManager.GetString("LogOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to البريد.
        /// </summary>
        public static string Mail {
            get {
                return ResourceManager.GetString("Mail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الإدارة.
        /// </summary>
        public static string Manage {
            get {
                return ResourceManager.GetString("Manage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إدارة المهام.
        /// </summary>
        public static string ManageMissions {
            get {
                return ResourceManager.GetString("ManageMissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إدارة الاذونات.
        /// </summary>
        public static string ManagePermissions {
            get {
                return ResourceManager.GetString("ManagePermissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إدارة الأنتاجية.
        /// </summary>
        public static string ManageProductivity {
            get {
                return ResourceManager.GetString("ManageProductivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المدير.
        /// </summary>
        public static string Manager {
            get {
                return ResourceManager.GetString("Manager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إدارة الرواتب.
        /// </summary>
        public static string ManageSalary {
            get {
                return ResourceManager.GetString("ManageSalary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إدارة الاجازات.
        /// </summary>
        public static string ManageVacations {
            get {
                return ResourceManager.GetString("ManageVacations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الأنتاجية الغير مسجلة.
        /// </summary>
        public static string MissingProductivity {
            get {
                return ResourceManager.GetString("MissingProductivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المهام.
        /// </summary>
        public static string Missions {
            get {
                return ResourceManager.GetString("Missions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قائمة المهام.
        /// </summary>
        public static string MissionsList {
            get {
                return ResourceManager.GetString("MissionsList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مهامي.
        /// </summary>
        public static string MyMissions {
            get {
                return ResourceManager.GetString("MyMissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الأذونات الخاصة بي.
        /// </summary>
        public static string MyPermissions {
            get {
                return ResourceManager.GetString("MyPermissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الإنتاجية الخاصة بي.
        /// </summary>
        public static string MyProductivity {
            get {
                return ResourceManager.GetString("MyProductivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الراتب الخاص بي.
        /// </summary>
        public static string MySalary {
            get {
                return ResourceManager.GetString("MySalary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الأجازات الخاصة بي.
        /// </summary>
        public static string MyVacations {
            get {
                return ResourceManager.GetString("MyVacations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الجنسية.
        /// </summary>
        public static string Nationality {
            get {
                return ResourceManager.GetString("Nationality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to كلمة المرور الجديدة.
        /// </summary>
        public static string NewPassword {
            get {
                return ResourceManager.GetString("NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to كلمة المرور القديمة.
        /// </summary>
        public static string OldPassword {
            get {
                return ResourceManager.GetString("OldPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الأذونات.
        /// </summary>
        public static string Permissions {
            get {
                return ResourceManager.GetString("Permissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قائمة الأذونات.
        /// </summary>
        public static string PermissionsList {
            get {
                return ResourceManager.GetString("PermissionsList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to البيانات الأساسية.
        /// </summary>
        public static string PrimaryInformation {
            get {
                return ResourceManager.GetString("PrimaryInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الإنتاجية.
        /// </summary>
        public static string Productivity {
            get {
                return ResourceManager.GetString("Productivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الأنتاجية بالتاريخ.
        /// </summary>
        public static string ProductivityByDate {
            get {
                return ResourceManager.GetString("ProductivityByDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الأنتاجية بالمشروع.
        /// </summary>
        public static string ProductivityByProject {
            get {
                return ResourceManager.GetString("ProductivityByProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قائمة الأنتاجية.
        /// </summary>
        public static string ProductivityList {
            get {
                return ResourceManager.GetString("ProductivityList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المشروعات.
        /// </summary>
        public static string Projects {
            get {
                return ResourceManager.GetString("Projects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أنواع المشروعات.
        /// </summary>
        public static string ProjectTypes {
            get {
                return ResourceManager.GetString("ProjectTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أعتيادي.
        /// </summary>
        public static string Regular {
            get {
                return ResourceManager.GetString("Regular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إعادة تعيين.
        /// </summary>
        public static string Reset {
            get {
                return ResourceManager.GetString("Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دفعات الرواتب.
        /// </summary>
        public static string SalaryBatches {
            get {
                return ResourceManager.GetString("SalaryBatches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حفظ.
        /// </summary>
        public static string SaveChanges {
            get {
                return ResourceManager.GetString("SaveChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بحث.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إظهار الفروع.
        /// </summary>
        public static string ShowBranches {
            get {
                return ResourceManager.GetString("ShowBranches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الأهداف.
        /// </summary>
        public static string Target {
            get {
                return ResourceManager.GetString("Target", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المهام.
        /// </summary>
        public static string Tasks {
            get {
                return ResourceManager.GetString("Tasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المستخدمين.
        /// </summary>
        public static string Users {
            get {
                return ResourceManager.GetString("Users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إدارة المستخدمين.
        /// </summary>
        public static string UsersManagement {
            get {
                return ResourceManager.GetString("UsersManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قائمة الأجازات.
        /// </summary>
        public static string VacationsList {
            get {
                return ResourceManager.GetString("VacationsList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أنواع الأجازات.
        /// </summary>
        public static string VacationTypes {
            get {
                return ResourceManager.GetString("VacationTypes", resourceCulture);
            }
        }
    }
}
